- name: AMQ Event Listener
  hosts: localhost
  execution_strategy: parallel
  sources:
    - mancubus77.events.amq:
        host: "172.23.3.25"
        port: "31016"
        channel: "hello"
        username: "user"
        password: "password"

  rules:
    - name: Print Rule
      condition:
        all:
          - events.webhook << event.webhook.payload.url == "http://www.example.com"
          - events.kafka << event.kafka.message.channel == "red"
      action:
        print_event:
          pretty: true
          var_root: i
